spring.application.name=health-diet-management
server.port=8080

spring.datasource.url=jdbc:sqlite:data.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

gemini.api.key=${GEMINI_API_KEY:}
gemini.model=gemini-2.5-flash-lite
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models
